name: Build .NET Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish executable
      run: dotnet publish -c Release -r win-x64 --self-contained

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: ./bin/Release/net6.0/win-x64/publish/
