name: "Build .NET Framework application and release"

on:
  push:
    branches: [ gh-actions-test ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.1
      
    - name: Build the solution
      run: .\build.ps1
      shell: powershell